<template>
  <AppLayout>
    <section class="path-page" v-loading="loading">
      <header class="page-header"><div><p class="eyebrow">PERSONAL ROADMAP</p><h3>学习路径</h3><p>按知识点依次推进；完成一个节点，就能让后续学习更有依据。</p></div><el-button type="primary" :loading="generating" @click="generatePath">{{ pathKps.length ? '重新生成路径' : '生成学习路径' }}</el-button></header>
      <div v-if="!pathKps.length && !loading" class="empty"><div class="empty-icon">🗺️</div><h4>还没有学习路径</h4><p>系统会根据当前知识库创建一条可执行的学习路线。</p><el-button type="primary" @click="generatePath">开始规划</el-button></div>
      <div v-else class="path-timeline"><article v-for="(kp,index) in pathKps" :key="kp.id" class="path-node" :class="nodeState(kp)"><div class="node-rail"><span class="node-dot">{{ nodeState(kp) === 'done' ? '✓' : index + 1 }}</span><i v-if="index < pathKps.length-1"></i></div><div class="node-card"><div class="node-title"><div><h4>{{ kp.name }}</h4><p>{{ kp.description || '完成学习后可在诊断中查看掌握度。' }}</p></div><el-tag size="small" effect="plain">{{ kp.category || '通用' }}</el-tag></div><div class="node-progress"><el-progress :percentage="Math.round(kp.mastery * 100)" :stroke-width="7" :status="kp.mastery >= .8 ? 'success' : undefined" /><span>{{ masteryText(kp.mastery) }}</span></div><div class="node-actions"><el-button text type="primary" @click="$router.push({path:'/courses',query:{cat:kp.category}})">开始学习</el-button><el-button text @click="$router.push({path:'/chat',query:{q:`请为我讲解知识点“${kp.name}”，并给出学习要点和两道练习题。`}})">问 AI</el-button></div></div></article></div>
    </section>
  </AppLayout>
</template>

<script setup>
import { onMounted, ref } from "vue"
import { ElMessage } from "element-plus"
import AppLayout from "../components/AppLayout.vue"
import { apiGet, apiPost } from "../utils/api"
import { ensureLearner } from "../utils/learner"

const loading = ref(false), generating = ref(false), learner = ref(null), pathKps = ref([])
const masteryText = mastery => mastery >= .8 ? "已掌握" : mastery >= .4 ? "学习中" : "待学习"
const nodeState = kp => kp.mastery >= .8 ? "done" : kp.mastery > 0 ? "active" : "todo"
async function hydratePath(plan) { const [pathData,kpData,masteryData] = await Promise.all([apiGet(`/learning/plans/${plan.id}/knowledge-points`),apiGet("/learning/knowledge-points"),apiGet(`/learning/learners/${learner.value.id}/mastery`)]); const kps = new Map((kpData || []).map(kp => [kp.id,kp])); const mastery = new Map((masteryData.data || []).map(row => [row.kp_id,row.level])); pathKps.value = (pathData.data || []).map(row => ({ ...(kps.get(row.kp_id) || { id:row.kp_id,name:row.kp_id }), mastery: mastery.get(row.kp_id) || 0 })) }
async function loadPath() { loading.value=true; try { learner.value ||= await ensureLearner(); const plans = await apiGet(`/learning/plans?learner_id=${learner.value.id}`); const plan = (plans.data || []).find(item => item.status !== "archived"); if (plan) await hydratePath(plan) } catch (error) { ElMessage.error(error.message || "学习路径加载失败") } finally { loading.value=false } }
async function generatePath() { generating.value=true; try { learner.value ||= await ensureLearner(); const kps = await apiGet("/learning/knowledge-points"); if (!kps?.length) return ElMessage.warning("请先在课程中心导入或添加学习内容"); const plan = await apiPost("/learning/plans", { learner_id:learner.value.id, goal:"当前知识库学习路线" }); const selected = [...kps].sort((a,b) => Number(a.difficulty || 0) - Number(b.difficulty || 0)).slice(0,12); await Promise.all(selected.map((kp,index) => apiPost(`/learning/plans/${plan.id}/knowledge-points`, { kp_id:kp.id, sort_order:index }))); await hydratePath({ id:plan.id }); ElMessage.success("学习路径已生成") } catch (error) { ElMessage.error(error.message || "路径生成失败") } finally { generating.value=false } }
onMounted(loadPath)
</script>

<style scoped>
.path-page { max-width:850px; margin:0 auto }.page-header { display:flex; justify-content:space-between; align-items:flex-start; gap:16px; margin-bottom:24px }.eyebrow { margin:0 0 4px; color:var(--accent-primary); font-size:11px; font-weight:700; letter-spacing:1.2px }.page-header h3 { margin:0 0 6px; font-size:22px }.page-header p:not(.eyebrow) { margin:0; color:var(--text-secondary); font-size:14px }.empty { padding:72px 20px; text-align:center; border:1px dashed var(--border-color); border-radius:var(--radius-xl); background:var(--bg-secondary) }.empty-icon { font-size:42px }.empty h4 { margin:10px 0 5px; font-size:17px }.empty p { margin:0 0 18px; color:var(--text-secondary); font-size:13px }.path-timeline { padding:3px 0 }.path-node { display:grid; grid-template-columns:45px 1fr; min-height:122px }.node-rail { position:relative; display:flex; justify-content:center }.node-rail i { position:absolute; top:34px; bottom:-2px; width:2px; background:var(--border-color) }.node-dot { z-index:1; width:30px; height:30px; display:grid; place-items:center; color:var(--text-secondary); border:2px solid var(--border-color); border-radius:50%; background:var(--bg-primary); font-size:12px; font-weight:700 }.active .node-dot { color:var(--accent-primary); border-color:var(--accent-primary) }.done .node-dot { color:#fff; border-color:var(--success); background:var(--success) }.done .node-rail i { background:var(--success) }.node-card { padding:16px; margin-bottom:14px; border:1px solid var(--border-color); border-radius:var(--radius-lg); background:var(--bg-secondary) }.node-title { display:flex; align-items:flex-start; justify-content:space-between; gap:12px }.node-title h4 { margin:0 0 5px; font-size:15px }.node-title p { margin:0; color:var(--text-secondary); font-size:13px; line-height:1.45 }.node-progress { display:flex; align-items:center; gap:10px; margin-top:13px }.node-progress :deep(.el-progress) { flex:1 }.node-progress span { color:var(--text-tertiary); font-size:12px; white-space:nowrap }.node-actions { margin-top:7px; text-align:right } @media(max-width:640px) { .page-header { flex-direction:column }.path-node { grid-template-columns:36px 1fr }.node-title { flex-direction:column; gap:6px }.node-card { padding:14px } }
</style>
